stages:
  - build

build:
  stage: build
  image: docker:stable
  services:
    - name: docker:dind
  variables:
    DOCKER_DRIVER: overlay2
    IMAGE_NAME: backend
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker pull $IMAGE_NAME:latest || true
    - docker build --cache-from "$IMAGE_NAME:latest" --tag "$IMAGE_NAME:$CI_BUILD_REF" --tag "$IMAGE_NAME:latest" .
    - docker push "$IMAGE_NAME:$CI_BUILD_REF"
    - docker push "$IMAGE_NAME:latest"
  only:
    - master
