version: '2.1'

services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped

  django:
    image: fotcorn/liveinconcert-backend
    environment:
      - "DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@postgres:5432/postgres"
      - "SECRET_KEY=${SECRET_KEY}"
      - "ALLOWED_HOSTS=${DOMAIN}"
      - "FIREBASE_CREDENTIALS_PATH=/etc/firebase_credentials.json"
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ./credentials.json:/etc/firebase_credentials.json
  caddy:
    image: abiosoft/caddy
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    environment:
      - "DOMAIN=${DOMAIN}"
    volumes:
    - ./Caddyfile:/etc/Caddyfile
    restart: unless-stopped
