# Generated by Django 2.0.8 on 2018-09-14 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spotifyprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='spotifyprofile',
            name='refresh_token',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
