# Generated by Django 2.0.8 on 2018-09-14 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_auto_20180914_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spotifyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='spotify_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
