# Generated by Django 2.0.8 on 2018-09-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('push', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firebasepushtoken',
            name='token',
            field=models.TextField(unique=True),
        ),
    ]
