# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 17:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArtistRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Love'), (2, 'Like'), (3, 'Know'), (4, 'Do not like')])),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liveinconcert.Artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('artist__name',),
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('location', models.CharField(max_length=500, verbose_name='Location')),
                ('date_time', models.DateTimeField(verbose_name='Date & Time')),
                ('bandsintown_id', models.CharField(blank=True, max_length=100, null=True, verbose_name=b'BandsInTown ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liveinconcert.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='EventRSVP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsvp', models.IntegerField(choices=[(1, 'Yes'), (2, 'No'), (3, 'Unknown')])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liveinconcert.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
