# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveinconcert', '0002_auto_20151230_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='artist',
            name='songkick_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artistrating',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Love'), (2, 'Like'), (3, 'Know'), (4, 'Do not like'), (5, 'Not yet rated')]),
        ),
        migrations.AlterField(
            model_name='event',
            name='bandsintown_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='BandsInTown ID'),
        ),
    ]
