# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-13 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveinconcert', '0004_event_songkick_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventrsvp',
            unique_together=set([('event', 'user')]),
        ),
    ]
