# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-19 20:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liveinconcert', '0005_auto_20160213_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('songkick_id', models.IntegerField(blank=True, null=True, verbose_name='Songkick ID')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liveinconcert.Venue'),
        ),
    ]
