# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liveinconcert', '0006_auto_20160219_2014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('date_time',)},
        ),
    ]
